/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author Ekanayaketw
 */
public class AssignSupervisors extends javax.swing.JFrame {
    Connection con=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    /**
     * Creates new form StudentRegistration
     */
    public AssignSupervisors() {
        initComponents();
        
    }
       
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        reset = new javax.swing.JButton();
        add1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        spId = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        svname1 = new javax.swing.JTextField();
        contact = new javax.swing.JLabel();
        number = new javax.swing.JTextField();
        email = new javax.swing.JLabel();
        email_2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        stid = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        stdname = new javax.swing.JTextField();
        contact1 = new javax.swing.JLabel();
        Stdnumber = new javax.swing.JTextField();
        email1 = new javax.swing.JLabel();
        stdemail = new javax.swing.JTextField();
        campus = new javax.swing.JLabel();
        Campus = new javax.swing.JTextField();
        course = new javax.swing.JLabel();
        Course = new javax.swing.JTextField();
        year = new javax.swing.JLabel();
        Year = new javax.swing.JTextField();
        sem = new javax.swing.JLabel();
        Sem = new javax.swing.JTextField();
        email2 = new javax.swing.JLabel();
        dept = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        view = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        Demo1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        fake = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 51));
        setName("StudentRegistration"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Assign Supervisor Form");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 190, 30));

        reset.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel1.add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 600, -1, -1));

        add1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add1.setText("Add");
        add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add1ActionPerformed(evt);
            }
        });
        jPanel1.add(add1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 600, -1, -1));

        jLabel3.setText("Supervisor Id");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 80, 20));
        jPanel1.add(spId, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 210, 30));

        jLabel5.setText("Supervisor Name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 90, 20));
        jPanel1.add(svname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 210, 30));

        contact.setText("Contact Number");
        jPanel1.add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 90, 20));
        jPanel1.add(number, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 210, 30));

        email.setText("Email Address");
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 80, 20));
        jPanel1.add(email_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 210, 30));

        jLabel4.setText("Student Id");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 80, 20));
        jPanel1.add(stid, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 210, 30));

        jLabel6.setText("Student Name");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 80, 20));
        jPanel1.add(stdname, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, 210, 30));

        contact1.setText("Contact Number");
        jPanel1.add(contact1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 100, 20));
        jPanel1.add(Stdnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 210, 30));

        email1.setText("Email Address");
        jPanel1.add(email1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 100, 20));
        jPanel1.add(stdemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, 210, 30));

        campus.setText("Campus");
        jPanel1.add(campus, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 90, 20));
        jPanel1.add(Campus, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 210, 30));

        course.setText("Course");
        jPanel1.add(course, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 90, 20));
        jPanel1.add(Course, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 510, 210, 30));

        year.setText("Year");
        jPanel1.add(year, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 480, 40, 20));
        jPanel1.add(Year, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 470, 210, 30));

        sem.setText("Semester");
        jPanel1.add(sem, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 510, 50, 20));
        jPanel1.add(Sem, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 510, 210, 30));

        email2.setText("Department");
        jPanel1.add(email2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 80, 20));
        jPanel1.add(dept, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 210, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 580, 650));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel2.setPreferredSize(new java.awt.Dimension(548, 628));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        view.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        view.setText("View ");
        jPanel2.add(view, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 600, -1, -1));

        delete.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel2.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 600, -1, -1));

        edit.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        jPanel2.add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 600, -1, -1));

        Demo1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Demo1.setText("Demo");
        Demo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Demo1ActionPerformed(evt);
            }
        });
        jPanel2.add(Demo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, -1, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 530, 280));

        fake.setText("fake");
        jPanel2.add(fake, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 410, 50, 20));

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table1);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 530, 220));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, -1, 650));

        jLabel15.setText("<- LogOut");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 50, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/S_images/user.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 0, 50, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Demo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Demo1ActionPerformed
        // TODO add your handling code here:
        
        spId.setText("SPR15023156");
        svname1.setText("Bihandu Sanchith");
        number.setText("0772359578");
        email_2.setText("B@gmail.com");
        dept.setText("SE");
        stdname.setText("Lakshan Thilakarathne");
        stid.setText("IT15023156");
        Campus.setText("Malabe");
        Course.setText("Software Engineering");
        Year.setText("3");
        Sem.setText("2");
        Stdnumber.setText("0772359578");
        stdemail.setText("lakshan@gmail.com");
        
    }//GEN-LAST:event_Demo1ActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        
         spId.setText("");
        svname1.setText("");
        number.setText("");
        email_2.setText("");
        dept.setText("");
        stdname.setText("");
        stid.setText("");
        Campus.setText("");
        Course.setText("");
        Year.setText("");
        Sem.setText("");
        Stdnumber.setText("");
        stdemail.setText("");
        
    }//GEN-LAST:event_resetActionPerformed

    private void add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add1ActionPerformed
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_add1ActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        try{
        DefaultTableModel model=(DefaultTableModel)table.getModel();
         int row =table.getSelectedRow();
        
        String supervisor_ID = table.getValueAt(row,0).toString();
        String supervisor_name = table.getValueAt(row,1).toString();
        String contact = table.getValueAt(row,3).toString();
        String email = table.getValueAt(row,4).toString();
        
       

        spId.setText(supervisor_ID);
        svname1.setText(supervisor_name);
        number.setText(contact);
        dept.setText(email);
        }catch(Exception e){
            e.getMessage();
        }
       
                               
    }//GEN-LAST:event_tableMouseClicked

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
         int x = JOptionPane.showConfirmDialog(null, "Do you want to update this record");
        
        if (x==0){
            String id = spId.getText();
            String name = svname1.getText();
            String contact = number.getText();
            String dept_ = dept.getText();
            
            
           
            
            try{
                String sql = "update supervisorregistration set supervisor_name = '"+name+"',"
                        + "gender = '"+fake.getText()+"',"
                        + "contact_number = '"+contact+"',email = '"+dept_+"',"
                        + "where supervisor_id ='"+id+"'";
                pst =(PreparedStatement)con.prepareStatement(sql);
                pst.execute();
                //TableLoad();
            }catch(Exception e){
               e.getMessage();
            }
            
          
        }
                                  
    }//GEN-LAST:event_editActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        int x = JOptionPane.showConfirmDialog(null, "Do you want to delete this record");
        
        if (x==0){
            String id = spId.getText();
            
            
            try{
                String sql = "delete from supervisorregistration where supervisor_id ='"+id+"'";
                pst =(PreparedStatement)con.prepareStatement(sql);
                pst.execute();
                //TableLoad();
            }catch(Exception e){
               e.getMessage();
            }
            
          
        }
    }//GEN-LAST:event_deleteActionPerformed

    public void TableLoad() throws SQLException{
      
        try {
            String sql="select * from supervisorregistration";
            
            pst=(PreparedStatement) con.prepareStatement(sql);
            rs=pst.executeQuery();
            //.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            Logger.getLogger(StudentRegistration.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }
    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        Login l1=new Login();
        l1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel15MouseClicked

    private void table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_table1MouseClicked

    

        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AssignSupervisors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AssignSupervisors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AssignSupervisors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AssignSupervisors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AssignSupervisors().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Campus;
    private javax.swing.JTextField Course;
    private javax.swing.JButton Demo1;
    private javax.swing.JTextField Sem;
    private javax.swing.JTextField Stdnumber;
    private javax.swing.JTextField Year;
    private javax.swing.JButton add1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel campus;
    private javax.swing.JLabel contact;
    private javax.swing.JLabel contact1;
    private javax.swing.JLabel course;
    private javax.swing.JButton delete;
    private javax.swing.JTextField dept;
    private javax.swing.JButton edit;
    private javax.swing.JLabel email;
    private javax.swing.JLabel email1;
    private javax.swing.JLabel email2;
    private javax.swing.JTextField email_2;
    private javax.swing.JLabel fake;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField number;
    private javax.swing.JButton reset;
    private javax.swing.JLabel sem;
    private javax.swing.JTextField spId;
    private javax.swing.JTextField stdemail;
    private javax.swing.JTextField stdname;
    private javax.swing.JTextField stid;
    private javax.swing.JTextField svname1;
    private javax.swing.JTable table;
    private javax.swing.JTable table1;
    private javax.swing.JButton view;
    private javax.swing.JLabel year;
    // End of variables declaration//GEN-END:variables
}
