/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfaces;

import MainFiles.Dbconfig;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Asus
 */
public class Form_I07 extends javax.swing.JFrame {
    Connection con=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    /**
     * Creates new form Form_I07
     */
    public Form_I07() {
        initComponents();
        //connect with databse
         con=Dbconfig.connect();
         //call the tableload function
         tableload();
    }
    
    //load the database table data into from
     public void tableload()
    {
        try {
            String sql="select * from formnewi07";
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
            evaluation_table.setModel(DbUtils.resultSetToTableModel(rs));
            
            
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sid = new javax.swing.JTextField();
        sname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        sphone = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        semail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        ename = new javax.swing.JTextField();
        degree = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        spel = new javax.swing.JTextField();
        supname = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        internduration = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        credits = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        monthly = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        comments = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        interntitle = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        report = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        viva = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        grade = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        examinarname = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        total = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        evaluation_table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1500, 1000));
        setPreferredSize(new java.awt.Dimension(1000, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setText("Faculty Of Computing");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 470, 40));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Academic Information");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 190, 50));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("Student Performance Evaluation");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 360, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("Form I-07");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 170, 50));

        jLabel1.setText("Student ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, 160, -1));

        jLabel6.setText("Student Name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 160, -1));

        sid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sidActionPerformed(evt);
            }
        });
        getContentPane().add(sid, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 190, 300, -1));

        sname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snameActionPerformed(evt);
            }
        });
        getContentPane().add(sname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 300, -1));

        jLabel7.setText("Student Phone");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 160, -1));

        sphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sphoneActionPerformed(evt);
            }
        });
        getContentPane().add(sphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 300, -1));

        jLabel8.setText("Student Email");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 160, -1));

        semail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semailActionPerformed(evt);
            }
        });
        getContentPane().add(semail, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 230, 300, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Student Information");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 170, 50));

        jLabel10.setText("Employer's Name");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 160, -1));

        jLabel11.setText("Degree Title");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 160, -1));

        ename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enameActionPerformed(evt);
            }
        });
        getContentPane().add(ename, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 300, -1));

        degree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                degreeActionPerformed(evt);
            }
        });
        getContentPane().add(degree, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 300, -1));

        jLabel12.setText("Supervisor's Name");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, 160, -1));

        jLabel13.setText("Specialization");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 400, 160, -1));

        spel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spelActionPerformed(evt);
            }
        });
        getContentPane().add(spel, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 400, 300, -1));

        supname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supnameActionPerformed(evt);
            }
        });
        getContentPane().add(supname, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 310, 300, -1));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setText("Employer Information");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 190, 50));

        jLabel15.setText("Intenship Duration");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 160, -1));

        internduration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interndurationActionPerformed(evt);
            }
        });
        getContentPane().add(internduration, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, 300, -1));

        jLabel16.setText("No Of Credits");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 440, 160, -1));

        credits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditsActionPerformed(evt);
            }
        });
        getContentPane().add(credits, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 440, 300, -1));

        jLabel17.setText("Comments on how the internship benifited the student");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 430, -1));

        monthly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthlyActionPerformed(evt);
            }
        });
        getContentPane().add(monthly, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 670, 100, -1));

        jLabel18.setText("Monthly Progress(30%)");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 670, 180, -1));

        comments.setColumns(20);
        comments.setRows(5);
        jScrollPane1.setViewportView(comments);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 950, -1));

        jLabel19.setText("Intenship Title");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 160, -1));

        interntitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interntitleActionPerformed(evt);
            }
        });
        getContentPane().add(interntitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 480, 810, -1));

        jLabel20.setText("Internship Report(30%)");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 710, 180, -1));

        report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportActionPerformed(evt);
            }
        });
        getContentPane().add(report, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 710, 100, -1));

        jLabel21.setText("Viva(40%)");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 750, 180, -1));

        jButton1.setText("Total Marks");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 790, -1, -1));

        viva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vivaActionPerformed(evt);
            }
        });
        getContentPane().add(viva, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 750, 100, -1));

        jLabel22.setText("Final Grade");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 790, 180, -1));

        grade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradeActionPerformed(evt);
            }
        });
        getContentPane().add(grade, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 790, 100, -1));

        jLabel23.setText("Examinar's Name");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 850, 180, -1));

        examinarname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                examinarnameActionPerformed(evt);
            }
        });
        getContentPane().add(examinarname, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 850, 260, -1));

        jButton2.setText("Submit Form");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 880, -1, -1));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/S_images/user.png"))); // NOI18N
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 20, 50, 50));

        jLabel25.setText("<- LogOut");
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 70, -1, -1));

        jButton3.setText("Edit Details");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 880, -1, -1));
        getContentPane().add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 790, 100, 30));

        evaluation_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        evaluation_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                evaluation_tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(evaluation_table);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 190, -1, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sidActionPerformed

    private void snameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_snameActionPerformed

    private void sphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sphoneActionPerformed

    private void semailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semailActionPerformed

    private void enameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enameActionPerformed

    private void degreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_degreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_degreeActionPerformed

    private void spelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spelActionPerformed

    private void supnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supnameActionPerformed

    private void interndurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interndurationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_interndurationActionPerformed

    private void creditsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creditsActionPerformed

    private void monthlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthlyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthlyActionPerformed

    private void interntitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interntitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_interntitleActionPerformed

    private void reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reportActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        //calculate total marks
        
        Integer MProgress=Integer.parseInt(monthly.getText());
        Integer Ireport=Integer.parseInt(report.getText());
        Integer Viva=Integer.parseInt(viva.getText());
        
        Integer tot=MProgress+Ireport+Viva;
        String finaltot=tot.toString();
        total.setText(finaltot);
        
        if(tot>=75){
            grade.setText("A");
        }
        else if((tot>=65)&&(tot<=75)){
        grade.setText("B");
        }
        else if((tot>=55)&&(tot<=65)){
            grade.setText("C");
        }
        else{
            grade.setText("C-");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void vivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vivaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vivaActionPerformed

    private void gradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gradeActionPerformed

    private void examinarnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_examinarnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_examinarnameActionPerformed

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
        Login l1=new Login();
        l1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel25MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          
//        get text from text fields
        
        String student_ID_=sid.getText();
        String student_name_=sname.getText();
        String student_contact_=sphone.getText();
        String student_email_=semail.getText();
        String employer_name_=ename.getText();
        String supervisor_name_=supname.getText();
        String digree_type_=degree.getText();
        String  specialization_=spel.getText();
        String internship_duration_=internduration.getText();
        String no_of_credits_=credits.getText();
        String internship_title_=interntitle.getText();
        String comments_=comments.getText();
        String final_grade_=grade.getText();
        String examinar_name_=examinarname.getText();
        
        //check all the text fields are not null
        if((student_ID_.isEmpty())||(student_name_.isEmpty())||(student_contact_.isEmpty())||(student_email_.isEmpty())||(employer_name_.isEmpty())
                ||(supervisor_name_.isEmpty())||(digree_type_.isEmpty())||(specialization_.isEmpty())||(internship_duration_.isEmpty())||(no_of_credits_.isEmpty())||(internship_title_.isEmpty())
                        ||(comments_.isEmpty())||(final_grade_.isEmpty())||(examinar_name_.isEmpty())){
                     JOptionPane.showMessageDialog(null, "Fill all fields");
        }
        //checks the student id is starts with IT letters
        else if(!student_ID_.startsWith("IT")){
            JOptionPane.showMessageDialog(null, "Invalid IT number");
        }
        //checks the contact number size
        else if((student_contact_.length()!=10)){
            JOptionPane.showMessageDialog(null, "Invalid phone number");
        }

        else if(student_email_.indexOf('@')==0 || student_email_.indexOf('.')==0 ||student_email_.indexOf('@')>student_email_.indexOf('.')){
            JOptionPane.showMessageDialog(null, "Invalid email address");
        }

        else{
        //insert query
            try{
                 String q="Insert into formnewi07(student_ID,student_name,"
               + "student_contact,student_email,employer_name,"
               + "supervisor_name,digree_type,specialization,internship_duration,no_of_credits,internship_title,comments,final_grade,examinar_name)"
               + "values('"+student_ID_+"','"+student_name_+"','"+student_contact_+"'"
               + ",'"+student_email_+"','"+employer_name_+"',"
               + "'"+supervisor_name_+"','"+digree_type_+"',"
                         + "'"+specialization_+"','"+internship_duration_+"','"+no_of_credits_+"','"+internship_title_+"',"
                         + "'"+comments_+"','"+final_grade_+"','"+examinar_name_+"')";
               
//execute the insert query
              pst=(PreparedStatement) con.prepareStatement(q);
              pst.execute();
              tableload();
              JOptionPane.showMessageDialog(null, "successfully added");
                
            }catch(Exception e){
                e.getMessage();
            }
        }
        
        //set text field into null
            sid.setText("");
            sname.setText("");
            sphone.setText("");  
            semail.setText("");  
            ename.setText("");
            supname.setText("");
            degree.setText("");
            spel.setText("");
            internduration.setText("");
             credits.setText("");
              interntitle.setText("");
               comments.setText("");
                grade.setText("");
                 examinarname.setText("");
                 monthly.setText("");
                 report.setText("");
                 viva.setText("");
                 total.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         int x=JOptionPane.showConfirmDialog(null,"Do you really want to Update this record");
         
          if(x==0){
  
//        get text from text fields
        
        String student_ID_=sid.getText();
        String student_name_=sname.getText();
        String student_contact_=sphone.getText();
        String student_email_=semail.getText();
        String employer_name_=ename.getText();
        String supervisor_name_=supname.getText();
        String digree_type_=degree.getText();
        String  specialization_=spel.getText();
        String internship_duration_=internduration.getText();
        String no_of_credits_=credits.getText();
        String internship_title_=interntitle.getText();
        String comments_=comments.getText();
        String final_grade_=grade.getText();
        String examinar_name_=examinarname.getText();
           
        //check all the text fields are not null
        if((student_ID_.isEmpty())||(student_name_.isEmpty())||(student_contact_.isEmpty())||(student_email_.isEmpty())||(employer_name_.isEmpty())
                ||(supervisor_name_.isEmpty())||(digree_type_.isEmpty())||(specialization_.isEmpty())||(internship_duration_.isEmpty())||(no_of_credits_.isEmpty())||(internship_title_.isEmpty())
                        ||(comments_.isEmpty())||(final_grade_.isEmpty())||(examinar_name_.isEmpty())){
                     JOptionPane.showMessageDialog(null, "Fill all fields");
        }
        //checks the student id is starts with IT letters
        else if(!student_ID_.startsWith("IT")){
            JOptionPane.showMessageDialog(null, "Invalid IT number");
        } 
        //checks the contact number size
        else if((student_contact_.length()!=10)){
            JOptionPane.showMessageDialog(null, "Invalid phone number");
        }
        //checks the email is valid
        else if(student_email_.indexOf('@')==0 || student_email_.indexOf('.')==0 ||student_email_.indexOf('@')>student_email_.indexOf('.')){
            JOptionPane.showMessageDialog(null, "Invalid email address");
        }
       
        //update query
        else{
            String sql="Update formnewi07 set student_name='"+student_name_+"',student_contact='"+student_contact_+"',"
                    + "student_email='"+student_email_+"',employer_name='"+employer_name_+"',supervisor_name='"+supervisor_name_+"',"
                    + "digree_type='"+digree_type_+"',specialization='"+specialization_+"',internship_duration='"+internship_duration_+"',"
                    + "no_of_credits='"+no_of_credits_+"',internship_title='"+internship_title_+"',comments='"+comments_+"',"
                    + "final_grade='"+final_grade_+"',examinar_name='"+examinar_name_+"' where student_ID='"+student_ID_+"'";
           
            
             try {
                 //execute query
                 pst=(PreparedStatement) con.prepareStatement(sql);
            
                 pst.execute();
                 tableload();
                 JOptionPane.showMessageDialog(this, "You successfully updated your details");
                 

             } catch (Exception ex) {
                 ex.getMessage();
             }
        }
      
        
        //set text field into null
            sid.setText("");
            sname.setText("");
            sphone.setText("");  
            semail.setText("");  
            ename.setText("");
            supname.setText("");
            degree.setText("");
            spel.setText("");
            internduration.setText("");
             credits.setText("");
              interntitle.setText("");
               comments.setText("");
                grade.setText("");
                 examinarname.setText("");
                 monthly.setText("");
                 report.setText("");
                 viva.setText("");
                 total.setText("");
                 
                sid.setEditable(false); 
                sname.setEditable(false);
         }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void evaluation_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_evaluation_tableMouseClicked
       
        //mouce clicked event
        
        int r= evaluation_table.getSelectedRow();
         String student_id_=evaluation_table.getValueAt(r, 0).toString();
        String student_name_=evaluation_table.getValueAt(r, 1).toString();
        String student_contact_=evaluation_table.getValueAt(r, 2).toString();
        String student_email_=evaluation_table.getValueAt(r, 3).toString();
        String employer_name_=evaluation_table.getValueAt(r, 4).toString();
        String supervisor_name_=evaluation_table.getValueAt(r, 5).toString();
        String digree_type_=evaluation_table.getValueAt(r, 6).toString();
        String  specialization_=evaluation_table.getValueAt(r, 7).toString();
        String internship_duration_=evaluation_table.getValueAt(r, 8).toString();
         String no_of_credits_=evaluation_table.getValueAt(r, 9).toString();
        String internship_title_= evaluation_table.getValueAt(r, 10).toString();
        String comments_=evaluation_table.getValueAt(r, 11).toString();
        String final_grade_=evaluation_table.getValueAt(r, 12).toString();
        String examinar_name=evaluation_table.getValueAt(r, 13).toString();
        
   
        //set row values to text fields
                 sid.setText(student_id_);
                 sname.setText(student_name_);
                 sphone.setText(student_contact_);
                 semail.setText(student_email_);
                 ename.setText(employer_name_);
                 supname.setText(supervisor_name_);
                 degree.setText(digree_type_);
                 spel.setText(specialization_);
                 internduration.setText(internship_duration_);
                  credits.setText(no_of_credits_);
            interntitle.setText(internship_title_);
            comments.setText(comments_);
            grade.setText(final_grade_);
            examinarname.setText(examinar_name);
 
        
    }//GEN-LAST:event_evaluation_tableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_I07.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_I07.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_I07.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_I07.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_I07().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea comments;
    private javax.swing.JTextField credits;
    private javax.swing.JTextField degree;
    private javax.swing.JTextField ename;
    private javax.swing.JTable evaluation_table;
    private javax.swing.JTextField examinarname;
    private javax.swing.JTextField grade;
    private javax.swing.JTextField internduration;
    private javax.swing.JTextField interntitle;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField monthly;
    private javax.swing.JTextField report;
    private javax.swing.JTextField semail;
    private javax.swing.JTextField sid;
    private javax.swing.JTextField sname;
    private javax.swing.JTextField spel;
    private javax.swing.JTextField sphone;
    private javax.swing.JTextField supname;
    private javax.swing.JLabel total;
    private javax.swing.JTextField viva;
    // End of variables declaration//GEN-END:variables
}
